name: After On Pull Request

on:
  workflow_run:
    workflows: ["On Pull Request"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: write secret
        run: echo ${{ secrets.SURGE_TOKEN }} > 2.txt

      - name: cat secret
        run: cat 2.txt
