# This workflow runs on target, so there is no need to worry about secrets
name: Website Preview Deploy

on:
  workflow_run:
    workflows: ["Website Preview"]
    types: [completed]

jobs:
  # Build successfully, start deployment
  on-success:
    name: Build successfully
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    env:
      PULL_REQUEST_NUMBER: ${{ github.event.workflow_run.pull_requests.number }}
    steps:
      - name: Show event
        run: |
          echo "github event is $GITHUB_JSON"
        env:
          GITHUB_JSON: ${{ toJSON(github.event) }}

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: website
          run_id: ${{ github.event.workflow_run.id }}
          workflow: ${{ github.event.workflow_run.workflow_id }}

      - name: Deploy Site
        run: |
          echo "PULL_REQUEST_NUMBER is $PULL_REQUEST_NUMBER"
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

      - name: Deploy has succeeded
        if: ${{ success() }}
        run: |
          echo "PULL_REQUEST_NUMBER is $PULL_REQUEST_NUMBER"
        env:
          BOT_URL: ${{ secrets.BOT_URL }}

      - name: Deploy has failed
        if: ${{ failure() }}
        run: |
          echo "PULL_REQUEST_NUMBER is $PULL_REQUEST_NUMBER"
        env:
          BOT_URL: ${{ secrets.BOT_URL }}

  # Build failed, update comment
  on-failure:
    name: Build failed
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    env:
      PULL_REQUEST_NUMBER: ${{ github.event.workflow_run.pull_requests.number }}
    steps:
      - name: Update comment
        run: |
          echo "PULL_REQUEST_NUMBER is $PULL_REQUEST_NUMBER"
        env:
          BOT_URL: ${{ secrets.BOT_URL }}
