name: Website Preview

on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PULL_REQUEST_NUMBER: ${{ github.event.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn

      - name: Build website
        run: echo ${PULL_REQUEST_NUMBER} > dist/version.html

      - name: Deploy Site
        run: |
          export DEPLOY_DOMAIN=https://preview-${PULL_REQUEST_NUMBER}-test-adaex.surge.sh
          echo "Deploy to $DEPLOY_DOMAIN"
          npx surge --project ./dist --domain $DEPLOY_DOMAIN --token ${{ secrets.SURGE_TOKEN }}

      - name: Deploy has failed
        if: ${{ failure() }}
        run: echo "failed"